- name: Create Kubernetes Cluster
  hosts: localhost
  vars:
    state_store: "s3://anu-kops-state-store-25"  # <<< personalize this
    cluster_name: "dev.k8s.local"
  tasks:
    - name: Create cluster
      shell: |
        export KOPS_STATE_STORE={{ state_store }}
        kops create cluster \
          --name {{ cluster_name }} \
          --zones us-east-1a,us-east-1b \
          --node-count 2 \
          --node-size t2.medium \
          --master-size t2.medium \
          --dns-zone={{ cluster_name }} \
          --yes

    - name: Wait for cluster to be ready
      command: kops validate cluster --name={{ cluster_name }}
      register: result
      until: result.rc == 0
      retries: 20
      delay: 60
      environment:
        KOPS_STATE_STORE: "{{ state_store }}"