[kubernetes_master]
master ansible_host=3.87.182.160 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/tom-key.pem

[kubernetes_workers]
worker1 ansible_host=3.82.228.247 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/tom-key.pem
worker2 ansible_host=54.204.109.93 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/tom-key.pem

[kubernetes_cluster:children]
kubernetes_master
kubernetes_workers