[kubernetes_master]
master ansible_host=3.87.182.160 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/tom-key.pem

[kubernetes_workers]
worker1 ansible_host=3.82.228.247 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/tom-key.pem
worker2 ansible_host=54.204.109.93 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/tom-key.pem

[kubernetes_cluster:children]
kubernetes_master
kubernetes_workers

[local]
ansible_master ansible_host=44.202.241.86 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/tom.pem