# Instance that uses tom key
[tom_instances]
worker_tom ansible_host=18.233.155.145 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/tom.pem

# We'll need to find/create the KOPS key for these instances
[kops_instances]
master ansible_host=54.175.131.33 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/kops_key.pem
worker1 ansible_host=54.173.246.80 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/kops_key.pem
worker2 ansible_host=3.85.59.6 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/kops_key.pem

[kubernetes_cluster:children]
tom_instances
kops_instances
